name: CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: latest
      - uses: actions/checkout@v2
      - run: docker run -p "2379:2379" -p "2380:2380" -e ALLOW_NONE_AUTHENTICATION=yes -d bitnami/etcd:3
      - run: shards install
      - run: crystal spec
      - run: crystal tool format --check
      - run: ./bin/ameba

